// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"go-store/types"
	"math/rand/v2"
)

func Base(products []types.Product) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><head><title>Go Webstore</title><link rel=\"stylesheet\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("assets/styles/styles.css?%d", rand.IntN(10000)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/base.templ`, Line: 14, Col: 97}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><form action=\"/purchase\" method=\"post\"><fieldset><legend>Personal Info</legend> <label for=\"fname\">First name:</label><br><input type=\"text\" id=\"fname\" name=\"fname\" pattern=\"[A-Za-z\\s&#39;]+\" title=\"Only letters, spaces, and apostrophes allowed\" required><br><label for=\"lname\">Last name:</label><br><input type=\"text\" id=\"lname\" name=\"lname\" pattern=\"[A-Za-z\\s&#39;]+\" title=\"Only letters, spaces, and apostrophes allowed\" required><br><label for=\"email\">Email:</label><br><input type=\"email\" id=\"email\" name=\"email\" required><br></fieldset><fieldset><legend>Product Info</legend> <select name=\"product\" id=\"product\"><option diabled selected>-- Select a Product -- </option><option value=\"diapers\" data-image=\"diapers.jpg\" data-stock=\"3\">diapers - $30.00</option> <option value=\"pacifier\" data-image=\"pacifier.jpg\" data-stock=\"10\">pacifier - $10.00</option></select><br><label for=\"quantity\">Quantity:</label><br><input type=\"number\" id=\"quantity\" name=\"quantity\" min=\"1\" max=\"100\" value=\"1\" required><br><div id=\"image-container\" style=\"display:none;\"><img id=\"product-image\" src=\"\" alt=\"Product Image\" style=\"max-width:300px;\"></div></fieldset><fieldset><legend>Round up for donation</legend> <label><input type=\"radio\" name=\"donation\" value=\"yes\"> Yes, round up for donation</label><br><label><input type=\"radio\" name=\"donation\" value=\"no\" checked> No, thank you</label></fieldset><button type=\"submit\">Purchase</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\n            function setCookie(name, value, daysToLive) {\n                let cookie = name + \"=\" + encodeURIComponent(value);\n                if (typeof daysToLive === \"number\") {\n                    cookie += \"; max-age=\" + (daysToLive * 24 * 60 * 60);\n                }\n                document.cookie = cookie;\n            }\n\n            function getCookie(name) {\n                let cookieArr = document.cookie.split(\";\");\n                for (let i = 0; i < cookieArr.length; i++) {\n                    let cookiePair = cookieArr[i].split(\"=\");\n                    if (name == cookiePair[0].trim()) {\n                        return decodeURIComponent(cookiePair[1]);\n                    }\n                }\n                return null;\n            }\n\n\n            const userEmail = getCookie(\"user_email\");\n            if (userEmail) {\n                console.log(\"User is logged in: \", userEmail);\n            } else {\n                console.log(\"User is not logged in\");\n            }\n\n            document.getElementById('product').addEventListener('change', function() {\n                const selectedOption = this.options[this.selectedIndex];\n                const imageSrc = selectedOption.getAttribute('data-image');\n                const imgElement = document.getElementById('product-image');\n                const imgContainer = document.getElementById('image-container');\n                \n                if (imageSrc) {\n                    imgElement.src = 'assets/images/' + imageSrc;\n                    imgElement.alt = selectedOption.text;\n                    imgContainer.style.display = 'block';\n                } else {\n                    imgElement.src = '';\n                    imgContainer.style.display = 'none';\n                }\n            });\n        </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
