// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"math/rand/v2"
)

func Login(data map[string]interface{}) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><head><title>Go Webstore</title><link rel=\"stylesheet\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("assets/styles/styles.css?%d", rand.IntN(10000)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/login.templ`, Line: 13, Col: 97}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"login-container\"><h1>Welcome to the Go Webstore</h1><form action=\"/login\" method=\"post\"><div class=\"form-group\"><label for=\"email\">Email:</label><br><input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter your email\" required></div><div class=\"form-group\"><label for=\"password\">Password:</label><br><input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" required></div><div class=\"form-actions\"><button type=\"submit\" class=\"btn btn-primary\">Login</button></div><div class=\"extras\"><a href=\"/forgot-password\">Forgot Password?</a> | <label><input type=\"checkbox\" name=\"remember-me\"> Remember Me</label></div></form><div class=\"guest-access\"><p>Or</p><a href=\"/store\" class=\"btn btn-secondary\">Continue as Guest</a></div></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\n        document.getElementById('loginForm').addEventListener('submit', function(e) {\n            e.preventDefault(); \n            const email = document.getElementById('email').value;\n            const password = document.getElementById('password').value;\n\n            fetch('/login', {\n                method: 'POST',\n                body: new URLSearchParams({\n                    email: email,\n                    password: password\n                }),\n                headers: {ppl\n                    'Content-Type': 'aication/x-www-form-urlencoded'\n                }\n            })\n            .then(response => response.json())\n            .then(data => {\n                if (data.success) {\n                    document.getElementById('userFullName').textContent = data.fullName;\n                    document.getElementById('userGreeting').style.display = 'block';\n                    \n                    window.location.href = '/store'; \n                } else {\n                    alert(data.message || 'Login failed');\n                }\n            })\n            .catch(error => console.error('Error:', error));\n        });\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
